const elementdb = {
    1: {
        "name": "Hydrogen",
        "shortname": "H",
        "atomicnum": 1,
        "column": 1,
        "row": 1,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
        "series": "reactive_nonmetals",
        "group": "gas",
        "energylevels": "1",
        "weight": "1.008",
        "electro_negativity": "2.20",
        "meltingpoint": "-259.1", // In Celcius
        "boilingpoint": "-252.9", // In Celcius
        "electronaffinity": "72.8",
        "radius": "53", // In PM (Calculated)
        "hardness": "N/A", // In MPa (Brinnel)
        "modulus": "N/A", // In GPa (Bulk)
        "density": "0.0899", // In kg/m^3 (STP)
        "conductivity": "0.1805", // In W/mK (Thermal)
        "heat": "14,300", // In J/kgK (specific)
        "abundance": "75", // In Percentage (Universe)
        "discovered": "1808 AD",
    },
    18: {
        "name": "Helium",
        "shortname": "He",
        "atomicnum": 2,
        "column": 18,
        "row": 1,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    19: {
        "name": "Lithium",
        "shortname": "Li",
        "atomicnum": 3,
        "column": 1,
        "row": 2,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    20: {
        "name": "Berilium",
        "shortname": "Be",
        "atomicnum": 4,
        "column": 2,
        "row": 2,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    31: {
        "name": "Boron",
        "shortname": "B",
        "atomicnum": 5,
        "column": 13,
        "row": 2,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    32: {
        "name": "Carbon",
        "shortname": "C",
        "atomicnum": 6,
        "column": 14,
        "row": 2,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    33: {
        "name": "Nitrogen",
        "shortname": "N",
        "atomicnum": 7,
        "column": 15,
        "row": 2,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    34: {
        "name": "Oxygen",
        "shortname": "O",
        "atomicnum": 8,
        "column": 16,
        "row": 2,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    35: {
        "name": "Fluorine",
        "shortname": "F",
        "atomicnum": 9,
        "column": 17,
        "row": 2,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    36: {
        "name": "Neon",
        "shortname": "Ne",
        "atomicnum": 10,
        "column": 18,
        "row": 2,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    37: {
        "name": "Sodium",
        "shortname": "Na",
        "atomicnum": 11,
        "column": 1,
        "row": 3,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    38: {
        "name": "Magnesium",
        "shortname": "Mg",
        "atomicnum": 12,
        "column": 2,
        "row": 3,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    49: {
        "name": "Alminium",
        "shortname": "Al",
        "atomicnum": 13,
        "column": 13,
        "row": 3,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    50: {
        "name": "Silicon",
        "shortname": "Si",
        "atomicnum": 14,
        "column": 14,
        "row": 3,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    51: {
        "name": "Phosphorus",
        "shortname": "P",
        "atomicnum": 15,
        "column": 15,
        "row": 3,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    52: {
        "name": "Sulfur",
        "shortname": "S",
        "atomicnum": 16,
        "column": 16,
        "row": 3,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    53: {
        "name": "Chlorine",
        "shortname": "Cl",
        "atomicnum": 17,
        "column": 17,
        "row": 3,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    54: {
        "name": "Argon",
        "shortname": "Ar",
        "atomicnum": 18,
        "column": 18,
        "row": 3,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    55: {
        "name": "Potasium",
        "shortname": "K",
        "atomicnum": 19,
        "column": 1,
        "row": 4,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    56: {
        "name": "Calcium",
        "shortname": "Ca",
        "atomicnum": 20,
        "column": 2,
        "row": 4,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    57: {
        "name": "Scandium",
        "shortname": "Sc",
        "atomicnum": 21,
        "column": 3,
        "row": 4,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    58: {
        "name": "Titanium",
        "shortname": "Ti",
        "atomicnum": 22,
        "column": 4,
        "row": 4,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    59: {
        "name": "Vanadium",
        "shortname": "V",
        "atomicnum": 23,
        "column": 5,
        "row": 4,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    60: {
        "name": "Chromium",
        "shortname": "Cr",
        "atomicnum": 24,
        "column": 6,
        "row": 4,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    61: {
        "name": "Manganese",
        "shortname": "Mn",
        "atomicnum": 25,
        "column": 7,
        "row": 4,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    62: {
        "name": "Iron",
        "shortname": "Fe",
        "atomicnum": 26,
        "column": 8,
        "row": 4,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    63: {
        "name": "Cobalt",
        "shortname": "Co",
        "atomicnum": 27,
        "column": 9,
        "row": 4,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    64: {
        "name": "Nickel",
        "shortname": "Ni",
        "atomicnum": 28,
        "column": 10,
        "row": 4,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    65: {
        "name": "Copper",
        "shortname": "Cu",
        "atomicnum": 29,
        "column": 11,
        "row": 4,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    66: {
        "name": "Zinc",
        "shortname": "Zn",
        "atomicnum": 30,
        "column": 12,
        "row": 4,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    67: {
        "name": "Galium",
        "shortname": "Ga",
        "atomicnum": 31,
        "column": 13,
        "row": 4,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    68: {
        "name": "Germanium",
        "shortname": "Ge",
        "atomicnum": 32,
        "column": 14,
        "row": 4,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    69: {
        "name": "Arsenic",
        "shortname": "As",
        "atomicnum": 33,
        "column": 15,
        "row": 4,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    70: {
        "name": "Selenium",
        "shortname": "Se",
        "atomicnum": 34,
        "column": 16,
        "row": 4,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    71: {
        "name": "Bromine",
        "shortname": "Br",
        "atomicnum": 35,
        "column": 17,
        "row": 4,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    72: {
        "name": "Krypton",
        "shortname": "Kr",
        "atomicnum": 36,
        "column": 18,
        "row": 4,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    73: {
        "name": "Rubidium",
        "shortname": "Rb",
        "atomicnum": 37,
        "column": 1,
        "row": 5,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    74: {
        "name": "Stron",
        "shortname": "Sr",
        "atomicnum": 38,
        "column": 2,
        "row": 5,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    75: {
        "name": "Yttrium",
        "shortname": "Y",
        "atomicnum": 39,
        "column": 3,
        "row": 5,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    76: {
        "name": "Zirconium",
        "shortname": "Zr",
        "atomicnum": 40,
        "column": 4,
        "row": 5,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    77: {
        "name": "Niobium",
        "shortname": "Nb",
        "atomicnum": 41,
        "column": 5,
        "row": 5,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    78: {
        "name": "Molybdenum",
        "shortname": "Mo",
        "atomicnum": 42,
        "column": 6,
        "row": 5,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    79: {
        "name": "Technetium",
        "shortname": "TC",
        "atomicnum": 43,
        "column": 7,
        "row": 5,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    80: {
        "name": "Ruthenium",
        "shortname": "Ru",
        "atomicnum": 44,
        "column": 8,
        "row": 5,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    81: {
        "name": "Rhodium",
        "shortname": "Rh",
        "atomicnum": 45,
        "column": 9,
        "row": 5,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    82: {
        "name": "Palladium",
        "shortname": "Pd",
        "atomicnum": 46,
        "column": 10,
        "row": 5,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    83: {
        "name": "Silver",
        "shortname": "Ag",
        "atomicnum": 47,
        "column": 11,
        "row": 5,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    84: {
        "name": "Cadmium",
        "shortname": "Cd",
        "atomicnum": 48,
        "column": 12,
        "row": 5,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    85: {
        "name": "Indium",
        "shortname": "In",
        "atomicnum": 49,
        "column": 13,
        "row": 5,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    86: {
        "name": "Tin",
        "shortname": "Sn",
        "atomicnum": 50,
        "column": 14,
        "row": 5,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    87: {
        "name": "Antimony",
        "shortname": "Sn",
        "atomicnum": 51,
        "column": 15,
        "row": 5,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    88: {
        "name": "Tellurium",
        "shortname": "Te",
        "atomicnum": 52,
        "column": 16,
        "row": 5,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    89: {
        "name": "Iodine",
        "shortname": "I",
        "atomicnum": 53,
        "column": 17,
        "row": 5,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    90: {
        "name": "Xenon",
        "shortname": "Xe",
        "atomicnum": 54,
        "column": 18,
        "row": 5,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    91: {
        "name": "Caesium",
        "shortname": "Cs",
        "atomicnum": 55,
        "column": 1,
        "row": 6,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    92: {
        "name": "Barium",
        "shortname": "Ba",
        "atomicnum": 56,
        "column": 2,
        "row": 6,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    94: {
        "name": "Hafnium",
        "shortname": "Hf",
        "atomicnum": 72,
        "column": 4,
        "row": 6,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    95: {
        "name": "Tantulum",
        "shortname": "Ta",
        "atomicnum": 73,
        "column": 5,
        "row": 6,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    96: {
        "name": "Tungsten",
        "shortname": "W",
        "atomicnum": 74,
        "column": 6,
        "row": 6,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    97: {
        "name": "Rhenium",
        "shortname": "Re",
        "atomicnum": 75,
        "column": 7,
        "row": 6,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    98: {
        "name": "Osmium",
        "shortname": "Os",
        "atomicnum": 76,
        "column": 8,
        "row": 6,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    99: {
        "name": "Irdium",
        "shortname": "Ir",
        "atomicnum": 77,
        "column": 9,
        "row": 6,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    100: {
        "name": "Platinum",
        "shortname": "Pt",
        "atomicnum": 78,
        "column": 10,
        "row": 6,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    101: {
        "name": "Gold",
        "shortname": "Au",
        "atomicnum": 79,
        "column": 11,
        "row": 6,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    102: {
        "name": "Mercury",
        "shortname": "Hg",
        "atomicnum": 80,
        "column": 12,
        "row": 6,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    103: {
        "name": "Thallium",
        "shortname": "Tl",
        "atomicnum": 81,
        "column": 13,
        "row": 6,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    104: {
        "name": "Lead",
        "shortname": "Pb",
        "atomicnum": 82,
        "column": 14,
        "row": 6,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    105: {
        "name": "Bismuth",
        "shortname": "Bi",
        "atomicnum": 83,
        "column": 15,
        "row": 6,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    106: {
        "name": "Polonium",
        "shortname": "Po",
        "atomicnum": 84,
        "column": 16,
        "row": 6,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    107: {
        "name": "Astatine",
        "shortname": "At",
        "atomicnum": 85,
        "column": 17,
        "row": 6,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    108: {
        "name": "Radon",
        "shortname": "Rn",
        "atomicnum": 86,
        "column": 18,
        "row": 6,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    109: {
        "name": "Francium",
        "shortname": "Fr",
        "atomicnum": 87,
        "column": 1,
        "row": 7,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    110: {
        "name": "Radium",
        "shortname": "Ra",
        "atomicnum": 88,
        "column": 2,
        "row": 7,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    112: {
        "name": "Rutherfordium",
        "shortname": "Rf",
        "atomicnum": 104,
        "column": 4,
        "row": 7,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    113: {
        "name": "Dubnium",
        "shortname": "Db",
        "atomicnum": 105,
        "column": 5,
        "row": 7,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    114: {
        "name": "Seaborgium",
        "shortname": "Sg",
        "atomicnum": 106,
        "column": 6,
        "row": 7,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    115: {
        "name": "Bohrium",
        "shortname": "Bh",
        "atomicnum": 107,
        "column": 7,
        "row": 7,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    116: {
        "name": "Hassium",
        "shortname": "Hs",
        "atomicnum": 108,
        "column": 8,
        "row": 7,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    117: {
        "name": "Meitnerium",
        "shortname": "Rf",
        "atomicnum": 109,
        "column": 9,
        "row": 7,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    118: {
        "name": "Darmstadtium",
        "shortname": "Ds",
        "atomicnum": 110,
        "column": 10,
        "row": 7,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    119: {
        "name": "Roentgenium",
        "shortname": "Rg",
        "atomicnum": 111,
        "column": 11,
        "row": 7,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    120: {
        "name": "Copernicium",
        "shortname": "Cn",
        "atomicnum": 112,
        "column": 12,
        "row": 7,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    121: {
        "name": "Nihonium",
        "shortname": "Nh",
        "atomicnum": 113,
        "column": 13,
        "row": 7,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    122: {
        "name": "Flerovium",
        "shortname": "Fl",
        "atomicnum": 114,
        "column": 14,
        "row": 7,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    123: {
        "name": "Moscovium",
        "shortname": "Mc",
        "atomicnum": 115,
        "column": 15,
        "row": 7,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    124: {
        "name": "Livermorium",
        "shortname": "Lv",
        "atomicnum": 116,
        "column": 16,
        "row": 7,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    125: {
        "name": "Tennessine",
        "shortname": "Ts",
        "atomicnum": 117,
        "column": 17,
        "row": 7,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
    126: {
        "name": "Oganesson",
        "shortname": "Og",
        "atomicnum": 118,
        "column": 18,
        "row": 7,
        "hoverbg": "lib/assets/elgifs/atom-gif-18.gif",
    },
}